# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-21 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casos',
            fields=[
                ('sr', models.BigIntegerField(db_column='SR', primary_key=True, serialize=False)),
                ('fecha', models.CharField(blank=True, max_length=40, null=True)),
                ('clli', models.CharField(blank=True, db_column='CLLI', max_length=25, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('ing_telmex', models.CharField(blank=True, max_length=60, null=True)),
                ('ing_cisco', models.CharField(blank=True, max_length=60, null=True)),
                ('problema_detalle', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tecnologia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('localizacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cluster_ce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='divisional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clli', models.CharField(max_length=25)),
                ('ip_lb0', models.CharField(max_length=15)),
                ('ip_lb1', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=6)),
                ('avm', models.IntegerField()),
                ('sofware_version', models.CharField(max_length=15)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.central')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cluster_ce')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('divisional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.divisional')),
            ],
        ),
        migrations.CreateModel(
            name='modelo_equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tecnologia', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelo_equipo'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estado'),
        ),
        migrations.AddField(
            model_name='central',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ciudad'),
        ),
    ]
