# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-25 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='casos',
        ),
    ]
