# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-25 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_casos'),
    ]

    operations = [
        migrations.CreateModel(
            name='casos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.BigIntegerField()),
                ('cobo', models.CharField(max_length=25, null=True)),
                ('fecha', models.CharField(max_length=40, null=True)),
                ('mes', models.CharField(max_length=8, null=True)),
                ('anio', models.IntegerField(null=True)),
                ('ing_telmex', models.CharField(max_length=60, null=True)),
                ('ing_cisco', models.CharField(max_length=60, null=True)),
                ('problema', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=20, null=True)),
                ('codigo_cierre', models.CharField(max_length=20, null=True)),
                ('subtipo', models.CharField(max_length=20, null=True)),
                ('detalle_subtipo', models.CharField(max_length=20, null=True)),
                ('tecnologia', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
