# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_casos'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casos',
            name='cobo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
