# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180926_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='clli',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
