# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_casos_clli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='codigo_cierre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
