# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180927_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='detalle_subtipo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='casos',
            name='subtipo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
