# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180927_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('divisional', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('ccentral', models.CharField(max_length=30)),
                ('cluster_ce', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=25)),
                ('ip_lb0', models.CharField(max_length=15)),
                ('casos', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
    ]
