# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_inventario'),
        ('optical', '0004_sub_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipo_optical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clli', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=15)),
                ('ne_id', models.CharField(max_length=15)),
                ('area_div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical.area_divisional')),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.central')),
            ],
        ),
    ]
