# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0006_auto_20181011_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo_optical',
            name='network_id',
        ),
        migrations.AddField(
            model_name='equipo_optical',
            name='sub_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optical.sub_network'),
        ),
    ]
