# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-12 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0007_auto_20181011_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_optical',
            name='software_version',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
