# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-12 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0010_auto_20181012_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario_opticos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('clli', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=15)),
                ('ne_id', models.CharField(max_length=15)),
                ('dir_divisional', models.CharField(max_length=30)),
                ('area_divisional', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('central', models.CharField(max_length=30)),
                ('cliente', models.CharField(max_length=30)),
                ('modelo_equipo', models.CharField(max_length=40)),
                ('software_version', models.CharField(max_length=25)),
                ('sub_network', models.CharField(max_length=40)),
                ('network_partition', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'inventario_opticos',
                'managed': False,
            },
        ),
    ]
