# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0011_inventario_opticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localizacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
