# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0012_auto_20181016_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario_piezas_optica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne', models.CharField(max_length=10)),
                ('equipment_type', models.CharField(max_length=30)),
                ('actualEquipmentType', models.CharField(max_length=90)),
                ('physical_location', models.CharField(max_length=30)),
                ('hw_part_number', models.CharField(max_length=30)),
                ('sn', models.CharField(max_length=15)),
                ('equipment_state', models.CharField(max_length=15)),
                ('product_id', models.CharField(max_length=20)),
                ('mes', models.CharField(max_length=3)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
