# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0013_inventario_piezas_optica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_piezas_optica',
            old_name='actualEquipmentType',
            new_name='actual_equipment_type',
        ),
    ]
