# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0014_auto_20190309_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_piezas_optica',
            name='mes',
            field=models.IntegerField(),
        ),
    ]
