# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0015_auto_20190309_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_piezas_optica',
            name='ne',
            field=models.CharField(max_length=15),
        ),
    ]
