# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0016_auto_20190309_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_piezas_optica',
            name='equipment_state',
            field=models.CharField(max_length=20),
        ),
    ]
