# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0018_auto_20190309_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_piezas_optica',
            name='id_ne',
            field=models.IntegerField(null=True),
        ),
    ]
