# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0019_inventario_piezas_optica_id_ne'),
    ]

    operations = [
        migrations.CreateModel(
            name='partes_optica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=25)),
                ('product_desc', models.CharField(max_length=75)),
                ('tecnology', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=15)),
                ('end_support', models.DateField()),
            ],
        ),
    ]
