# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0020_partes_optica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_piezas_optica',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
    ]
