# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0021_auto_20190521_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='version_inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
