# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-10 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce', '0002_auto_20181010_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
